DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR, AGE VARCHAR);

INSERT INTO ACCOUNT (NAME, AGE) VALUES ('NAME1', '11');
INSERT INTO ACCOUNT (NAME, AGE) VALUES ('NAME2', '12');
INSERT INTO ACCOUNT (NAME, AGE) VALUES ('NAME3', '13');
INSERT INTO ACCOUNT (NAME, AGE) VALUES ('NAME4', '14');