spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cosmos_database?useSSL=false&serverTimezone=UTC
    username: root
    password: 111111

logging:
  level:
    root: info

server:
  port: 8090
